app/bundles/ReportBundle/Form/Type/ReportFiltersType.php
<?php

namespace Mautic\ReportBundle\Form\Type;

use Mautic\ReportBundle\Form\DataTransformer\ReportFilterDataTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReportFiltersType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->addModelTransformer(
            new ReportFilterDataTransformer($options['filters'])
        );
    }

    /**
     * @return string
     */
    public function getParent()
    {
        return CollectionType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'filters' => [],
                'report'  => null,
            ]
        );
    }
}

app/bundles/ReportBundle/Controller/ReportController.php
<?php

namespace Mautic\ReportBundle\Controller;

use Mautic\CoreBundle\Controller\FormController;
use Mautic\CoreBundle\Factory\PageHelperFactoryInterface;
use Mautic\CoreBundle\Form\Type\DateRangeType;
use Mautic\CoreBundle\Helper\DateTimeHelper;
use Mautic\CoreBundle\Helper\InputHelper;
use Mautic\ReportBundle\Crate\ReportDataResult;
use Mautic\ReportBundle\Entity\Report;
use Mautic\ReportBundle\Form\Type\DynamicFiltersType;
use Mautic\ReportBundle\Model\ExportResponse;
use Mautic\ReportBundle\Model\ReportModel;
use Mautic\ReportBundle\Scheduler\Model\FileHandler;
use Symfony\Component\HttpFoundation;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

class ReportController extends FormController
{
    /**
     * @param int $page
     *
     * @return HttpFoundation\JsonResponse|HttpFoundation\RedirectResponse|HttpFoundation\Response
     */
    public function indexAction(Request $request, PageHelperFactoryInterface $pageHelperFactory, $page = 1)
    {
        /* @type \Mautic\ReportBundle\Model\ReportModel $model */
        $model = $this->getModel('report');

        // set some permissions
        $permissions = $this->security->isGranted(
            [
                'report:reports:viewown',
                'report:reports:viewother',
                'report:reports:create',
                'report:reports:editown',
                'report:reports:editother',
                'report:reports:deleteown',
                'report:reports:deleteother',
                'report:reports:publishown',
                'report:reports:publishother',
            ],
            'RETURN_ARRAY'
        );

        if (!$permissions['report:reports:viewown'] && !$permissions['report:reports:viewother']) {
            return $this->accessDenied();
        }

        $this->setListFilters();

        $pageHelper        = $pageHelperFactory->make('mautic.report', $page);

        $limit  = $pageHelper->getLimit();
        $start  = $pageHelper->getStart();
        $search = $request->get('search', $request->getSession()->get('mautic.report.filter', ''));
        $filter = ['string' => $search, 'force' => []];
        $request->getSession()->set('mautic.report.filter', $search);

        if (!$permissions['report:reports:viewother']) {
            $filter['force'][] = ['column' => 'r.createdBy', 'expr' => 'eq', 'value' => $this->user->getId()];
        }

        $orderBy    = $request->getSession()->get('mautic.report.orderby', 'r.name');
        $orderByDir = $request->getSession()->get('mautic.report.orderbydir', 'DESC');
        $reports    = $model->getEntities(
            [
                'start'      => $start,
                'limit'      => $limit,
                'filter'     => $filter,
                'orderBy'    => $orderBy,
                'orderByDir' => $orderByDir,
            ]
        );

        $count = count($reports);
        if ($count && $count < ($start + 1)) {
            $lastPage  = $pageHelper->countPage($count);
            $returnUrl = $this->generateUrl('mautic_report_index', ['page' => $lastPage]);
            $pageHelper->rememberPage($lastPage);

            return $this->postActionRedirect(
                [
                    'returnUrl'       => $returnUrl,
                    'viewParameters'  => ['page' => $lastPage],
                    'contentTemplate' => 'Mautic\ReportBundle\Controller\ReportController::indexAction',
                    'passthroughVars' => [
                        'activeLink'    => '#mautic_report_index',
                        'mauticContent' => 'report',
                    ],
                ]
            );
        }

        $pageHelper->rememberPage($page);

        return $this->delegateView(
            [
                'viewParameters' => [
                    'searchValue' => $search,
                    'items'       => $reports,
                    'totalItems'  => $count,
                    'page'        => $page,
                    'limit'       => $limit,
                    'permissions' => $permissions,
                    'model'       => $model,
                    'tmpl'        => $request->isXmlHttpRequest() ? $request->get('tmpl', 'index') : 'index',
                    'security'    => $this->security,
                ],
                'contentTemplate' => '@MauticReport/Report/list.html.twig',
                'passthroughVars' => [
                    'activeLink'    => '#mautic_report_index',
                    'mauticContent' => 'report',
                    'route'         => $this->generateUrl('mautic_report_index', ['page' => $page]),
                ],
            ]
        );
    }

    /**
     * Clone an entity.
     *
     * @param int $objectId
     *
     * @return HttpFoundation\JsonResponse|HttpFoundation\RedirectResponse|HttpFoundation\Response
     */
    public function cloneAction(Request $request, $objectId)
    {
        /* @type \Mautic\ReportBundle\Model\ReportModel $model */
        $model  = $this->getModel('report');
        $entity = $model->getEntity($objectId);

        if (null != $entity) {
            if (!$this->security->isGranted('report:reports:create')
                || !$this->security->hasEntityAccess(
                    'report:reports:viewown',
                    'report:reports:viewother',
                    $entity->getCreatedBy()
                )
            ) {
                return $this->accessDenied();
            }

            $entity = clone $entity;
            $entity->setId(null);
            $entity->setIsPublished(false);
        }

        return $this->newAction($request, $entity);
    }

    /**
     * Deletes the entity.
     *
     * @return array<string, string|array<string, string>>|bool|HttpFoundation\JsonResponse|HttpFoundation\RedirectResponse|HttpFoundation\Response
     */
    public function deleteAction(Request $request, $objectId)
    {
        $page      = $request->getSession()->get('mautic.report.page', 1);
        $returnUrl = $this->generateUrl('mautic_report_index', ['page' => $page]);
        $flashes   = [];

        $postActionVars = [
            'returnUrl'       => $returnUrl,
            'viewParameters'  => ['page' => $page],
            'contentTemplate' => 'Mautic\ReportBundle\Controller\ReportController::indexAction',
            'passthroughVars' => [
                'activeLink'    => '#mautic_report_index',
                'mauticContent' => 'report',
            ],
        ];

        if (HttpFoundation\Request::METHOD_POST === $request->getMethod()) {
            $model = $this->getModel('report');
            \assert($model instanceof ReportModel);
            $entity = $model->getEntity($objectId);

            $check = $this->checkEntityAccess(
                $postActionVars,
                $entity,
                $objectId,
                ['report:reports:deleteown', 'report:reports:deleteother'],
                $model,
                'report'
            );
            if (true !== $check) {
                return $check;
            }

            $model->deleteEntity($entity);

            $identifier = $this->translator->trans($entity->getName());
            $flashes[]  = [
                'type'    => 'notice',
                'msg'     => 'mautic.core.notice.deleted',
                'msgVars' => [
                    '%name%' => $identifier,
                    '%id%'   => $objectId,
                ],
            ];
        } // else don't do anything

        return $this->postActionRedirect(
            array_merge(
                $postActionVars,
                [
                    'flashes' => $flashes,
                ]
            )
        );
    }

    /**
     * Deletes a group of entities.
     *
     * @return HttpFoundation\Response
     */
    public function batchDeleteAction(Request $request)
    {
        $page      = $request->getSession()->get('mautic.report.page', 1);
        $returnUrl = $this->generateUrl('mautic_report_index', ['page' => $page]);
        $flashes   = [];

        $postActionVars = [
            'returnUrl'       => $returnUrl,
            'viewParameters'  => ['page' => $page],
            'contentTemplate' => 'Mautic\ReportBundle\Controller\ReportController::indexAction',
            'passthroughVars' => [
                'activeLink'    => '#mautic_report_index',
                'mauticContent' => 'report',
            ],
        ];

        if (HttpFoundation\Request::METHOD_POST === $request->getMethod()) {
            $model = $this->getModel('report');
            \assert($model instanceof ReportModel);
            $ids       = json_decode($request->query->get('ids', '{}'));
            $deleteIds = [];

            // Loop over the IDs to perform access checks pre-delete
            foreach ($ids as $objectId) {
                $entity = $model->getEntity($objectId);

                if (null === $entity) {
                    $flashes[] = [
                        'type'    => 'error',
                        'msg'     => 'mautic.report.report.error.notfound',
                        'msgVars' => ['%id%' => $objectId],
                    ];
                } elseif (!$this->security->hasEntityAccess(
                    'report:reports:deleteown',
                    'report:reports:deleteother',
                    $entity->getCreatedBy()
                )
                ) {
                    $flashes[] = $this->accessDenied(true);
                } elseif ($model->isLocked($entity)) {
                    $flashes[] = $this->isLocked($postActionVars, $entity, 'report', true);
                } else {
                    $deleteIds[] = $objectId;
                }
            }

            // Delete everything we are able to
            if (!empty($deleteIds)) {
                $entities = $model->deleteEntities($deleteIds);

app/bundles/ReportBundle/Resources/views/FormTheme/Report/layout.html.twig
{% block _report_aggregators_entry_column_row %}
<div class="choice-wrapper col-xs-6" data-form-block="_report_aggregators_entry_column_row">
    <label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
    <select id="{{ form.vars.id }}" name="{{ form.vars.full_name }}" class="{{ form.vars.attr.class }}">
        {% for column in form.vars.choices %}
            <option value="{{ column.value|e }}" {% if column.value == form.vars.data %}selected{% endif %}>
                {{ column.label }}
            </option>
        {% endfor %}
    </select>
</div>
{% endblock %}

{% block _report_aggregators_entry_function_row %}
<div class="choice-wrapper col-xs-4" data-form-block="_report_aggregators_entry_function_row">
    <label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
    <select id="{{ form.vars.id }}"
            name="{{ form.vars.full_name }}"
            class="{{ form.vars.attr.class }}"
            onchange="Mautic.checkReportCondition('{{ form.vars.id }}')">
        {% for function in form.vars.choices %}
            <option value="{{ function.value|e }}" {% if function.value == form.vars.data %}selected{% endif %}>
                {{ function.label }}
            </option>
        {% endfor %}
    </select>
</div>
{% endblock %}

{% block _report_aggregators_row %}
{%- set hasErrors = form.vars.errors|length > 0 -%}
<div id="aggregatorsContainer" class="row" data-form-block="_report_aggregators_row">
    <div class="form-group col-md-12 {% if hasErrors %}has-error{% endif %}">
        {{ form_widget(form) }}
        {{ form_errors(form) }}
    </div>
    <div class="col-xs-12">
        <button id="aggregators-button"
                disabled
                type="button"
                class="btn btn-primary"
                onclick="Mautic.addReportRow('report_aggregators');">{{ 'mautic.report.report.label.function'|trans }}</button>
    </div>
</div>
{% endblock %}

{% block _report_filters_entry_column_row %}
<label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
<select id="{{ form.vars.id }}" name="{{ form.vars.full_name }}" class="{{ form.vars.attr.class }}">
    {% for column in form.vars.choices %}
      <option value="{{ column.value|e }}" {% if column.value == form.vars.data %}selected{% endif %}>
          {{ column.label }}
      </option>
    {% endfor %}
</select>
{% endblock %}

{% block _report_filters_entry_condition_row %}
<label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
<select id="{{ form.vars.id }}" name="{{ form.vars.full_name }}" class="{{ form.vars.attr.class }}" onchange="Mautic.checkReportCondition('{{ form.vars.id }}')">
    {% for condition in form.vars.choices %}
    <option value="{{ condition.value|e }}" {% if condition.value == form.vars.data %}selected{% endif %}>
        {{ condition.label }}
    </option>
    {% endfor %}
</select>
{% endblock %}

{% block _report_filters_entry_value_row %}
{%- set condition = form.parent.children.condition.vars.value -%}
<div class="form-group mb-0" data-form-block="_report_filters_entry_value_row">
    <label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
    <input type="text" id="{{ form.vars.id }}" name="{{ form.vars.full_name }}" class="{{ form.vars.attr.class }}"
    value="{% if form.vars.data is iterable %}{{ form.vars.data|join(', ')|e }}{% else %}{{ form.vars.data|e }}{% endif %}"
    {% if condition in ['empty', 'notEmpty'] %}disabled{% endif %} />
</div>
{% endblock %}

{% block _report_filters_row %}
{%- set hasErrors = form.vars.errors|length > 0 -%}
<div id="filterSelectorContainer" class="row" data-form-block="_report_filters_row">
    <div class="form-group col-md-12 {% if hasErrors %}has-error{% endif %}">
        {{ form_widget(form) }}
        {{ form_errors(form) }}
    </div>
    <div class="col-xs-12">
        <button type="button" class="btn btn-primary" onclick="Mautic.addReportRow('report_filters');">{{ 'mautic.report.report.label.addfilter'|trans }}</button>
    </div>
</div>
{% endblock %}

{% block _report_tableOrder_entry_column_row %}
<div class="choice-wrapper col-xs-6" data-form-block="_report_tableOrder_entry_column_row">
    <label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
    <select id="{{ form.vars.id }}" name="{{ form.vars.full_name }}" class="{{ form.vars.attr.class }}">
        {% for column in form.vars.choices %}
          <option value="{{ column.value|e }}" {% if column.value == form.vars.data %}selected{% endif %}>
              {{ column.label }}
          </option>
        {% endfor %}
    </select>
</div>
{% endblock %}

{% block _report_tableOrder_entry_direction_row %}
<div class="choice-wrapper col-xs-4" data-form-block="_report_tableOrder_entry_direction_row">
    <label class="{{ form.vars.label_attr.class }}" for="{{ form.vars.id }}">{{ form.vars.label|trans }}</label>
    <select id="{{ form.vars.id }}" name="{{ form.vars.full_name }}" class="{{ form.vars.attr.class }}">
        {% for direction in form.vars.choices %}
        <option value="{{ direction.value|e }}" {% if direction.value == form.vars.data %}selected{% endif %}>
            {{ direction.label }}
        </option>
        {% endfor %}
    </select>
</div>
{% endblock %}

{% block _report_tableOrder_row %}
{%- set hasErrors = form.vars.errors|length > 0 -%}
<div id="tableOrderContainer" class="row" data-form-block="_report_tableOrder_row">
    <div class="form-group col-md-12 {% if hasErrors %}has-error{% endif %}">
        {{ form_widget(form) }}
        {{ form_errors(form) }}
    </div>
    <div class="col-xs-12">
        <button type="button" class="btn btn-primary" onclick="Mautic.addReportRow('report_tableOrder');">{{ 'mautic.report.report.label.addtableorder'|trans }}</button>
    </div>
</div>
{% endblock %}

{% block aggregator_row %}
<div id="{{ form.vars.id }}_container" class="row mb-sm" data-form-block="aggregator_row">
    {{ form_row(form.vars.form.children.function) }}
    {{ form_row(form.vars.form.children.column) }}
    <div class="col-xs-1 mt-lg">
        <button type="button" class="btn btn-danger" onclick="Mautic.removeReportRow('{{ form.vars.id }}_container');" data-toggle="tooltip" title="{{ 'mautic.report.report.label.removefilter'|trans }}"><i class="fa fa-minus-square-o"></i></button>
    </div>
</div>
{% endblock %}

{% block filter_selector_row %}
{%- set inGroup = form.vars.data.glue is not defined or (form.vars.data.glue is defined and 'and' is same as form.vars.data.glue) -%}
<div class="panel {% if inGroup %}in-group{% endif %}" id="{{ form.vars.id }}_container" data-form-block="filter_selector_row">
    <div class="panel-heading">
        <div class="panel-glue col-sm-2 pl-0">
            {{ form_row(form.vars.form.children.glue) }}
        </div>
    </div>
    <div class="panel-body">
        <div class="row mb-sm">
            <div class="choice-wrapper col-xs-3">
                {{ form_row(form.vars.form.children.column) }}
            </div>
            <div class="choice-wrapper col-xs-2">
                {{ form_row(form.vars.form.children.condition) }}
            </div>
            <div class="choice-wrapper col-xs-4">
                {{ form_row(form.vars.form.children.value) }}
            </div>
            <div class="choice-wrapper col-xs-2">
                {{ form_row(form.vars.form.children.dynamic) }}
            </div>
            <div class="col-xs-1 mt-lg">
                <button type="button" class="btn btn-danger" onclick="Mautic.removeReportRow('{{ form.vars.id }}_container');" data-toggle="tooltip" title="{{ 'mautic.report.report.label.removefilter'|trans }}"><i class="fa fa-minus-square-o"></i></button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block table_order_row %}
<div id="{{ form.vars.id }}_container" class="row mb-sm" data-form-block="table_order_row">
    {{ form_row(form.vars.form.children.column) }}
    {{ form_row(form.vars.form.children.direction) }}
    <div class="col-xs-2 mt-lg">
        <button type="button" class="btn btn-danger" onclick="Mautic.removeReportRow('{{ form.vars.id }}_container');" data-toggle="tooltip" title="{{ 'mautic.report.report.label.removefilter'|trans }}"><i class="fa fa-minus-square-o"></i></button>
    </div>
</div>
{% endblock %}